export const SIDEBAR_ROUTES = [
  {
    name: 'Home',
    route: '/home',
    icon: 'home-icon',
    app: 'core',
    children: [],
  },
  {
    name: 'Users',
    route: '/users',
    icon: 'customers-icon',
    app: 'core',
    children: [],
  },
  {
    name: 'Loans',
    route: '/loans',
    icon: 'loan-icon',
    app: 'core',
    children: [],
  },
  {
    name: 'Wallets',
    route: '/wallets',
    icon: 'wallets-icon',
    app: 'core',
    children: [],
  },
  {
    name: 'Transactions',
    route: '/transactions',
    icon: 'transactions-icon',
    app: 'core',
    children: [],
  },
  {
    name: 'Reports',
    route: '/reports',
    icon: 'reports-icon',
    app: 'core',
    children: [],
  },
  {
    name: 'Push notifications',
    route: '/push-notifications',
    icon: 'push-notifications-icon',
    app: 'core',
    children: [],
  },
  {
    name: 'Admin Users',
    route: '/admin-users',
    icon: 'admin-users-icon',
    app: 'core',
    children: [],
  },
  {
    name: 'Activity logs',
    route: '/activity-logs',
    icon: 'activity-logs-icon',
    app: 'core',
    children: [],
  },
  {
    name: 'Settings',
    route: '/settings',
    icon: 'settings-icon',
    app: 'core',
    children: [],
  },
  {
    name: 'Dashboard',
    route: '/asset-flex/dashboard',
    icon: 'analytics-icon',
    app: 'asset-flex',
    children: [],
  },
  {
    name: 'Vendors',
    route: '/asset-flex/vendors',
    icon: 'cashier-icon',
    app: 'asset-flex',
    children: [],
  },
  {
    name: 'Customers',
    route: '/asset-flex/customers',
    icon: 'user-verify-icon',
    app: 'asset-flex',
    children: [],
  },
  {
    name: 'Loans',
    route: '/asset-flex/loans',
    icon: 'cash-icon',
    app: 'asset-flex',
    children: [],
  },
  {
    name: 'Loan Products',
    route: '/asset-flex/loan-products',
    icon: 'money-icon',
    app: 'asset-flex',
    children: [],
  },
  {
    name: 'Settlements',
    route: '/asset-flex/settlements',
    icon: 'receipt-text-icon',
    app: 'asset-flex',
    children: [],
  },
  {
    name: 'Payment Methods',
    route: '/asset-flex/payment-methods',
    icon: 'wallet-icon',
    app: 'asset-flex',
    children: [],
  },
  {
    name: 'Providers',
    route: '/asset-flex/identity-providers',
    icon: 'security-icon',
    app: 'asset-flex',
    children: [],
  },
  {
    name: 'Roles',
    route: '/asset-flex/roles',
    icon: 'admin-icon',
    app: 'asset-flex',
    children: [],
  },
  {
    name: 'Admin Users',
    route: '/asset-flex/admin-users',
    icon: 'add-user-icon',
    app: 'asset-flex',
    children: [],
  },
  {
    name: 'Settings',
    route: '/asset-flex/settings',
    icon: 'edit-icon',
    app: 'asset-flex',
    children: [],
  },
];
